import 'bootstrap/dist/css/bootstrap.min.css';
import buildHeader from './header.js';
import buildFooter from './footer.js';

const mainApp = document.querySelector('main#app');

const missingContent = `<h4>content missing...</h4>`;

function parseAndInject(element, html) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    element.innerHTML = ''; // clear
    element.append(...doc.body.childNodes);
}

function rawInject(element, html) {
    // Use innerHTML when you want minimal parsing overhead or intend to keep scripts/styles intact
    element.innerHTML = html;
}

function startApp() {

    try {
        buildHeader();
        parseAndInject(mainApp, `<h1>Injected content into main#app!</h1>
            <button class='btn btn-success'>Click Me</button>
            <p>This was generated by the inject component function.</p>` || missingContent);
        buildFooter();
        console.log('Parcel app is running...');
    } catch (e) {
        rawInject(mainApp, missingContent);
        console.error('Error starting app:', e);
    }
}

// Wait for window load for everything including images and subresources
if (document.readyState === 'complete') {
    startApp();
} else {
    window.addEventListener('load', startApp, { once: true });
}
function buildHeader() {
    parseAndInject(hdr, `<h1>Parcel App Header</h1>
    <nav>
        <ul>
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </nav>` || missingHeader);
}
function buildFooter() {
    const year = new Date().getFullYear();
    rawInject(`<p>&copy; ${year} Parcel App. All rights reserved.</p> ` || missingFooter);
}